# Generated by Django 5.0.3 on 2024-03-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondage_three', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionthree',
            name='correct_answer',
            field=models.CharField(default='A', max_length=200),
        ),
    ]
