# Generated by Django 5.0.3 on 2024-03-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondage_three', '0002_questionthree_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choixthree',
            name='choix',
            field=models.JSONField(),
        ),
    ]
