# Generated by Django 5.0.3 on 2024-03-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondage_one', '0002_remove_answer_choix_remove_sondage_options_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='choices',
        ),
        migrations.AddField(
            model_name='answer',
            name='choix',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='sondage',
            name='options',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
